# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: main

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  generate-diagnostic-badges:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci --ignore-scripts

      - name: setup expo
        uses: expo/expo-github-action@v7
        with:
          # WARNING: don't use latest version of expo or eas
          expo-version: 6.1.0
          eas-version: 3.3.2
          token: ${{ secrets.EXPO_TOKEN }}

      - name: set badge messages
        run: |
          eas diagnostics | awk 'BEGIN {FS=": ";OFS=";"} {value=$2;if(length($2) > 0){if($2 ~ " - "){split($2,s," - ");value=s[1]} else if($2 ~ " => "){split($2,s," => ");value=s[2]};gsub(/ /,"",$1);gsub(/ /,"",value);if($1 !~ "OS") {print $1,value}}}' > /tmp/eas-diagnostics && \
            echo "BADGE_MSG_NODE=$(awk 'BEGIN {FS=";"} {if($1 == "Node"){print $2}}' /tmp/eas-diagnostics)" >> $GITHUB_ENV && \
            echo "BADGE_MSG_REACT=$(awk 'BEGIN {FS=";"} {if($1 == "react"){print $2}}' /tmp/eas-diagnostics)" >> $GITHUB_ENV && \
            echo "BADGE_MSG_REACT_NATIVE=$(awk 'BEGIN {FS=";"} {if($1 == "react-native"){print $2}}' /tmp/eas-diagnostics)" >> $GITHUB_ENV && \
            echo "BADGE_MSG_EXPO=$(awk 'BEGIN {FS=";"} {if($1 == "expo"){print $2}}' /tmp/eas-diagnostics)" >> $GITHUB_ENV && \
            echo "BADGE_MSG_EXPO_CLI=$(awk 'BEGIN {FS=";"} {if($1 == "expo-cli"){print $2}}' /tmp/eas-diagnostics)" >> $GITHUB_ENV && \
            echo "BADGE_MSG_EAS_CLI=$(awk 'BEGIN {FS=";"} {if($1 == "eas-cli"){print $2}}' /tmp/eas-diagnostics)" >> $GITHUB_ENV

      - name: generate node version badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        if: github.ref_name == 'main'
        with:
          auth: ${{ secrets.DYNAMIC_BADGES_TOKEN }}
          gistID: a947a746a4fa385b020f446f30fea29a
          filename: my-bank-app_main_node-version.json
          label: node
          message: ${{ env.BADGE_MSG_NODE }}
          color: blue
          namedLogo: Node.js
          logoColor: white

      - name: generate node version badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.DYNAMIC_BADGES_TOKEN }}
          gistID: 0404e4cced06a0a0f090bf71deb65788
          filename: my-bank-app_dev_node-version.json
          label: node
          message: ${{ env.BADGE_MSG_NODE }}
          color: blue
          namedLogo: Node.js
          logoColor: white

      - name: generate react version badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        if: github.ref_name == 'main'
        with:
          auth: ${{ secrets.DYNAMIC_BADGES_TOKEN }}
          gistID: c0b7dfcdb22631b0cc2eb3719e7e10a4
          filename: my-bank-app_main_react-version.json
          label: react
          message: ${{ env.BADGE_MSG_REACT }}
          color: blue
          namedLogo: React
          logoColor: white

      - name: generate react version badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.DYNAMIC_BADGES_TOKEN }}
          gistID: f258b6158a2fd0b98edf0f22bcf9a659
          filename: my-bank-app_dev_react-version.json
          label: react
          message: ${{ env.BADGE_MSG_REACT }}
          color: blue
          namedLogo: React
          logoColor: white

      - name: generate react-native version badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        if: github.ref_name == 'main'
        with:
          auth: ${{ secrets.DYNAMIC_BADGES_TOKEN }}
          gistID: 5b5a8ac02163fcf824b44fccaa46e40a
          filename: my-bank-app_main_react-native-version.json
          label: react-native
          message: ${{ env.BADGE_MSG_REACT_NATIVE }}
          color: blue
          namedLogo: React
          logoColor: white

      - name: generate react-native version badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.DYNAMIC_BADGES_TOKEN }}
          gistID: 78fcd9e84d9751e375e27ea406764de5
          filename: my-bank-app_dev_react-native-version.json
          label: react-native
          message: ${{ env.BADGE_MSG_REACT_NATIVE }}
          color: blue
          namedLogo: React
          logoColor: white

      - name: generate expo-sdk version badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        if: github.ref_name == 'main'
        with:
          auth: ${{ secrets.DYNAMIC_BADGES_TOKEN }}
          gistID: 2c0e943789acc3c5d9adc5795394e6e1
          filename: my-bank-app_main_expo-version.json
          label: expo-sdk
          message: ${{ env.BADGE_MSG_EXPO }}
          color: blue
          namedLogo: Expo
          logoColor: white

      - name: generate expo-sdk version badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.DYNAMIC_BADGES_TOKEN }}
          gistID: 4e0837191574df5cb4786c179c77dd9c
          filename: my-bank-app_dev_expo-version.json
          label: expo-sdk
          message: ${{ env.BADGE_MSG_EXPO }}
          color: blue
          namedLogo: Expo
          logoColor: white

      - name: generate coverage badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        if: github.ref_name == 'main'
        with:
          auth: ${{ secrets.DYNAMIC_BADGES_TOKEN }}
          gistID: d275e3640d272d60ed7ab425b2f2c750
          filename: my-bank-app_main_coverage.json
          label: coverage
          message: 0%
          color: red
          namedLogo: Jest
          logoColor: white

      - name: generate coverage badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.DYNAMIC_BADGES_TOKEN }}
          gistID: 9b4b01124df2f136cead1415721be185
          filename: my-bank-app_dev_coverage.json
          label: coverage
          message: 0%
          color: red
          namedLogo: Jest
          logoColor: white

  test:
    runs-on: ubuntu-latest
    needs: [generate-diagnostic-badges]

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci --ignore-scripts

      - name: setup expo
        uses: expo/expo-github-action@v7
        with:
          # WARNING: don't use latest version of expo or eas
          expo-version: 6.1.0
          eas-version: 3.3.2
          token: ${{ secrets.EXPO_TOKEN }}

      - name: test
        # https://github.com/facebook/jest/issues/9324
        run: npm test -- --coverage

      - name: process coverage results
        run: |
          echo "BADGE_MSG_COVERAGE=$(npx ts-node ./scripts/cov-badge-helper.ts ./coverage/coverage-summary.json | awk 'BEGIN {FS=";"}{print $1}')" >> $GITHUB_ENV && \
            echo "BADGE_COLOR_COVERAGE=$(npx ts-node ./scripts/cov-badge-helper.ts ./coverage/coverage-summary.json | awk 'BEGIN {FS=";"}{print $2}' )" >> $GITHUB_ENV

      - name: generate coverage badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        if: github.ref_name == 'main'
        with:
          auth: ${{ secrets.DYNAMIC_BADGES_TOKEN }}
          gistID: d275e3640d272d60ed7ab425b2f2c750
          filename: my-bank-app_main_coverage.json
          label: coverage
          message: ${{ env.BADGE_MSG_COVERAGE }}%
          color: ${{ env.BADGE_COLOR_COVERAGE }}
          namedLogo: Jest
          logoColor: white

      - name: generate coverage badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.DYNAMIC_BADGES_TOKEN }}
          gistID: 9b4b01124df2f136cead1415721be185
          filename: my-bank-app_dev_coverage.json
          label: coverage
          message: ${{ env.BADGE_MSG_COVERAGE }}%
          color: ${{ env.BADGE_COLOR_COVERAGE }}
          namedLogo: Jest
          logoColor: white

  publish:
    runs-on: ubuntu-latest
    environment: 'eas-update'
    needs: [test]

    steps:
      - name: check for EXPO_TOKEN
        run: |
            if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
              echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
              exit 1
            fi

      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci --ignore-scripts

      - name: setup expo
        uses: expo/expo-github-action@v7
        with:
          # WARNING: don't use latest version of expo or eas
          expo-version: 6.1.0
          eas-version: 3.3.2
          token: ${{ secrets.EXPO_TOKEN }}

      - name: publish update
        run: eas update --auto --non-interactive
